---
repos:
    - repo: https://github.com/pre-commit/pre-commit-hooks.git
      rev: v2.2.1
      hooks:
          - id: trailing-whitespace
            args: [--markdown-linebreak-ext=md]
          - id: end-of-file-fixer
          - id: check-json
          - id: check-yaml
          - id: debug-statements
          - id: check-merge-conflict
    # backend specific
    - repo: https://gitlab.com/pycqa/flake8
      rev: 3.7.9
      hooks:
          - id: flake8
            name: flake8
            files: 'backend'
    - repo: https://github.com/asottile/seed-isort-config
      rev: v1.8.0
      hooks:
          - id: seed-isort-config
            args: [--settings-path=backend]
